### ISSUE TITLE
cannot get nor put data

### ISSUE THREAD

**Issue by i4ki** [edpin/upspin2tweet#1]
I can list metadata of my directory in the upspin2tweet dirserver, but I was unable to tweet...

```sh
λ> upspin ls upspin@upspin2tweet.com/_i4k_/
upspin@upspin2tweet.com/_i4k_/Access
upspin@upspin2tweet.com/_i4k_/cfg/
upspin@upspin2tweet.com/_i4k_/tweet
```

But any attempt to get data or write fail with i/o timeout:

```
λ> upspin cp tweet upspin@upspin2tweet.com/_i4k_/tweet
upspin: cp: upspin@upspin2tweet.com/_i4k_/tweet: client.Put: I/O error:
	upspin@upspin2tweet.com/_i4k_/Access: client.Get:
	client/clientutil.ReadAll:
	client/clientutil.ReadLocation:
	store/remote.Get("remote,upspin.upspin2tweet.com:8443"):
	rpc.Invoke: Post https://upspin.upspin2tweet.com:8443/api/Store/Get: dial tcp 138.68.7.61:8443: i/o timeout
```

I've tried set storeserver to upspin2tweet server also, but with no success...

```
λ> cat /home/i4k/upspin/config | grep storeserver
storeserver: remote,ephemeral.upspin2tweet.com
```

**Comment by edpin** [comment]
Hi @tiago4orion ,

Sorry about that. It was a last-minute configuration change that broke it. If you sign up again, it will work this time. I just tried on my account and I was having the same problem. It should be fixed now.  Please let me know.

Thanks.

**Comment by i4ki** [comment]
I tried again but now I'm having another problem =(

```
λ> upspin cp tweet upspin@upspin2tweet.com/_i4k_/tweet
upspin: cp: client.Put: I/O error:
	store/remote.Put("remote,ephemeral.upspin2tweet.com:443"):
	rpc.Invoke: 401 Unauthorized: rpc.SessionForRequest: invalid operation:
	user <my-email>@gmail.com:
	rpc.PublicUserKeyService:
	bind.KeyServer: service with transport "remote" not registered

ERROR: exit status 1
```

I need to reconfigure something in my upspin client?

Thanks!

**Comment by edpin** [comment]
No. This was a bug in the ephemeral storeserver. I just pushed a fix. Somewhere along the lines I dropped an important import.

It should work now. Will you retry and confirm, please?

Thanks for helping me test this!

**Comment by i4ki** [comment]
Sorry for the late reply.

It works now! Thank you.

https://twitter.com/_i4k_/status/843281478305767424

**Comment by edpin** [comment]
Good to know. Thanks.
